name: Android CI

on:
  push:
    branches: [ "exp" ]
  pull_request:
    branches: [ "exp" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./express/gradlew
    - name: Build with Gradle
      run: ./express/gradlew build
